- name: Ensure image directory exists
  file:
    path: "/var/lib/vz/template/iso"
    state: directory
    mode: '0755'

- name: Download cloud image
  get_url:
    url: "{{ image_url }}"
    dest: "/var/lib/vz/template/iso/{{ image_filename }}"
    mode: '0644'

- name: Create VM
  command: >
    qm create {{ vm_id }}
    --name {{ vm_name }}
    --memory {{ memory }}
    --cores {{ cores }}
    --net0 virtio,bridge={{ net_bridge }}

- name: Import disk
  command: >
    qm importdisk {{ vm_id }}
    /var/lib/vz/template/iso/{{ image_filename }}
    {{ storage }}

- name: Attach disk
  command: >
    qm set {{ vm_id }}
    --scsihw virtio-scsi-pci
    --scsi0 {{ storage }}:vm-{{ vm_id }}-disk-0

- name: Add cloud-init drive
  command: >
    qm set {{ vm_id }} --ide2 {{ storage }}:cloudinit

- name: Set boot and serial console
  command: >
    qm set {{ vm_id }}
    --boot c --bootdisk scsi0
    --serial0 socket --vga serial0

- name: Convert to template
  command: qm template {{ vm_id }}
