- name: Get existing VM IDs
  command: "qm list"
  register: vm_list

- name: Set VM ID dynamically
  set_fact:
    vm_id: "{{ ((vm_list.stdout_lines[1:] | map('regex_search', '^(\d+)', '\1') | map('int') | list) | max(default=8990) + 10) }}"

- name: Ensure ISO directory exists
  file:
    path: "{{ proxmox_iso_path }}"
    state: directory
    mode: '0755'

- name: Download cloud image
  get_url:
    url: "{{ image_url }}"
    dest: "{{ proxmox_iso_path }}/{{ image_filename }}"
    mode: '0644'

- name: Create VM
  command: >
    qm create {{ vm_id }}
    --name {{ os_name }}-{{ os_version }}
    --memory {{ memory }}
    --cores {{ cores }}
    --net0 virtio,bridge={{ net_bridge }}

- name: Import disk
  command: >
    qm importdisk {{ vm_id }}
    {{ proxmox_iso_path }}/{{ image_filename }}
    {{ proxmox_vm_disk_storage }}

- name: Attach disk
  command: >
    qm set {{ vm_id }}
    --scsihw virtio-scsi-pci
    --scsi0 {{ proxmox_vm_disk_storage }}:vm-{{ vm_id }}-disk-0

- name: Add cloud-init drive
  command: >
    qm set {{ vm_id }} --ide2 {{ proxmox_vm_disk_storage }}:cloudinit

- name: Set boot and serial console
  command: >
    qm set {{ vm_id }}
    --boot c --bootdisk scsi0
    --serial0 socket --vga serial0

- name: Convert to template
  command: qm template {{ vm_id }}
