os_name: "ubuntu"
os_version: "24.04"
image_url: ""
image_filename: ""

proxmox_storage_id: "mixedstore"
proxmox_storage_base_path: "/mnt/pve/{{ proxmox_storage_id }}"
proxmox_iso_path: "{{ proxmox_storage_base_path }}/template/iso"
proxmox_iso_volid: "{{ proxmox_storage_id }}:iso/{{ image_filename }}"
proxmox_vm_disk_storage: "{{ proxmox_storage_id }}"

memory: 1024
cores: 1
disk_size: 4G
net_bridge: "vmbr0"
